export default function DescriptionPopover() {
  return (
    <>
      <p className="flex items-center text-sm text-gray-500 dark:text-gray-400">
        This is just some informational text{" "}
        <button
          data-popover-target="popover-description"
          data-popover-placement="bottom-end"
          type="button"
        >
          <svg
            className="w-4 h-4 ml-2 text-gray-400 hover:text-gray-500"
            aria-hidden="true"
            fill="currentColor"
            viewBox="0 0 20 20"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              fillRule="evenodd"
              d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z"
              clipRule="evenodd"
            />
          </svg>
          <span className="sr-only">Show information</span>
        </button>
      </p>
      <div
        data-popover=""
        id="popover-description"
        role="tooltip"
        // className="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
        className="z-10 inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
      >
        <div className="p-3 space-y-2">
          <h3 className="font-semibold text-gray-900 dark:text-white">
            Activity growth - Incremental
          </h3>
          <p>
            Report helps navigate cumulative growth of community activities.
            Ideally, the chart should have a growing trend, as stagnating chart
            signifies a significant decrease of community activity.
          </p>
          <h3 className="font-semibold text-gray-900 dark:text-white">
            Calculation
          </h3>
          <p>
            For each date bucket, the all-time volume of activities is
            calculated. This means that activities in period n contain all
            activities up to period n, plus the activities generated by your
            community in period.
          </p>
          <a
            href="#"
            className="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700"
          >
            Read more{" "}
            <svg
              className="w-4 h-4 ml-1"
              aria-hidden="true"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fillRule="evenodd"
                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                clipRule="evenodd"
              />
            </svg>
          </a>
        </div>
        <div data-popper-arrow="" />
      </div>
    </>
  );
}
