type ArcPointObj {
	id: String!
	arcId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

type ArcPointObjConnection {
	items: [ArcPointObj]
	nextToken: String
}

type ChapterChatObj {
	id: String!
	chapterId: String!
	title: String!
	summary: String!
	time: String!
}

type ChapterChatObjConnection {
	items: [ChapterChatObj]
	nextToken: String
}

type ChapterRetroObj {
	id: String!
	chapterId: String!
	title: String!
	description: String!
	time: String!
}

type ChapterRetroObjConnection {
	items: [ChapterRetroObj]
	nextToken: String
}

type ChapterSceneObj {
	id: String!
	chapterId: String!
	title: String!
	description: String!
	variant: String!
}

type ChapterSceneObjConnection {
	items: [ChapterSceneObj]
	nextToken: String
}

type ChapterVerseObj {
	id: String!
	chapterId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

type ChapterVerseObjConnection {
	items: [ChapterVerseObj]
	nextToken: String
}

type ChatConversationObj {
	id: String!
	chatId: String!
	summary: String!
	time: String!
}

type ChatConversationObjConnection {
	items: [ChatConversationObj]
	nextToken: String
}

type ChatMemberObj {
	id: String!
	chatId: String!
	variant: String!
	userId: String
}

type ChatMemberObjConnection {
	items: [ChatMemberObj]
	nextToken: String
}

type ClusterMemberObj {
	id: String!
	clusterId: String!
	userId: String!
}

type ClusterMemberObjConnection {
	items: [ClusterMemberObj]
	nextToken: String
}

type ClusterUpdateObj {
	id: String!
	clusterId: String!
	title: String!
	description: String!
	time: String!
}

type ClusterUpdateObjConnection {
	items: [ClusterUpdateObj]
	nextToken: String
}

type CollectionResourceObj {
	id: String!
	userId: String!
	collectionId: String!
	title: String!
	description: String!
	file: FileElem
	note: NoteElem
	log: LogElem
	link: LinkElem
	variant: String!
}

type CollectionResourceObjConnection {
	items: [CollectionResourceObj]
	nextToken: String
}

type ConversationMessageObj {
	id: String!
	memberId: String!
	conversationId: String!
	time: String!
	message: String!
}

type ConversationMessageObjConnection {
	items: [ConversationMessageObj]
	nextToken: String
}

input CreateArcPointObjInput {
	arcId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

input CreateChapterChatObjInput {
	chapterId: String!
	title: String!
	summary: String!
	time: String!
}

input CreateChapterRetroObjInput {
	chapterId: String!
	title: String!
	description: String!
	time: String!
}

input CreateChapterSceneObjInput {
	chapterId: String!
	title: String!
	description: String!
	variant: String!
}

input CreateChapterVerseObjInput {
	chapterId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

input CreateChatConversationObjInput {
	chatId: String!
	summary: String!
	time: String!
}

input CreateChatMemberObjInput {
	chatId: String!
	variant: String!
	userId: String
}

input CreateClusterMemberObjInput {
	clusterId: String!
	userId: String!
}

input CreateClusterUpdateObjInput {
	clusterId: String!
	title: String!
	description: String!
	time: String!
}

input CreateCollectionResourceObjInput {
	userId: String!
	collectionId: String!
	title: String!
	description: String!
	variant: String!
	file: FileElemInput
	log: LogElemInput
	note: NoteElemInput
	link: LinkElemInput
	score: ScoreElemInput
}

input CreateConversationMessageObjInput {
	id: String!
	memberId: String!
	conversationId: String!
	time: String!
	message: String!
}

input CreateForumMemberObjInput {
	forumId: String!
	userId: String!
}

input CreateForumPostObjInput {
	forumId: String!
	title: String!
	description: String!
	time: String!
}

input CreateGalleryCollectionObjInput {
	galleryId: String!
	title: String!
	description: String!
}

input CreateGalleryMemberObjInput {
	galleryId: String!
	userId: String!
}

input CreateGalleryObjInput {
	userId: String!
	title: String!
	description: String!
	thumbnail: FileElemInput
}

input CreateHorizonArcObjInput {
	horizonId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

input CreateHorizonClusterObjInput {
	horizonId: String!
	parentCluster: String
	title: String!
	description: String!
	time: String!
}

input CreateHorizonForumObjInput {
	horizonId: String!
	title: String!
	description: String!
	time: String!
}

input CreateHorizonMemberObjInput {
	horizonId: String!
	userId: String!
}

input CreateHorizonObjInput {
	userId: String!
	title: String!
	time: String!
	description: String!
	variant: String!
	thumbnail: FileElemInput
}

input CreateHorizonUpdateObjInput {
	horizonId: String!
	title: String!
	description: String!
	time: String!
}

input CreatePostCommentObjInput {
	postId: String!
	title: String!
	description: String!
	time: String!
}

input CreateReservationObjInput {
	fname: String!
	lname: String!
	email: String!
}

input CreateRetroContributionObjInput {
	retroId: String!
	variant: String!
	conversationId: String
	sceneId: String
	ideaId: String
	verseId: String
	value: Int!
	message: String!
	time: String!
}

input CreateRetroMemberObjInput {
	retroId: String!
	userId: String!
}

input CreateSceneIdeaObjInput {
	sceneId: String!
	userId: String!
	title: String!
	description: String!
	x: Int!
	y: Int!
	variant: String!
	file: FileElemInput
	log: LogElemInput
	note: NoteElemInput
	link: LinkElemInput
	score: ScoreElemInput
}

input CreateSpaceChapterObjInput {
	spaceId: String!
	title: String!
	description: String!
	idx: Int!
	thumbnail: FileElemInput!
}

input CreateSpaceMemberObjInput {
	spaceId: String!
	userId: String!
}

input CreateSpaceObjInput {
	userId: String!
	title: String!
	time: String!
	description: String!
	variant: String!
}

input CreateUserObjInput {
	fname: String!
	lname: String!
	passwordHash: String
	email: String!
	googleId: String
	customerId: String
	subscriptionId: String
	priceId: String
	created: String!
	profilePicture: FileElemInput
}

input CreateVerseCommentObjInput {
	userId: String!
	verseId: String!
	time: String!
	message: String!
}

input CreateVerseMemberObjInput {
	verseId: String!
	userId: String!
}

input DeleteArcPointObjInput {
	id: String!
}

input DeleteChapterChatObjInput {
	id: String!
}

input DeleteChapterRetroObjInput {
	id: String!
}

input DeleteChapterSceneObjInput {
	id: String!
}

input DeleteChapterVerseObjInput {
	id: String!
}

input DeleteChatConversationObjInput {
	id: String!
}

input DeleteChatMemberObjInput {
	id: String!
}

input DeleteClusterMemberObjInput {
	id: String!
}

input DeleteClusterUpdateObjInput {
	id: String!
}

input DeleteCollectionResourceObjInput {
	id: String!
}

input DeleteConversationMessageObjInput {
	id: String!
}

input DeleteForumMemberObjInput {
	id: String!
}

input DeleteForumPostObjInput {
	id: String!
}

input DeleteGalleryCollectionObjInput {
	id: String!
}

input DeleteGalleryMemberObjInput {
	id: String!
}

input DeleteGalleryObjInput {
	id: String!
}

input DeleteHorizonArcObjInput {
	id: String!
}

input DeleteHorizonClusterObjInput {
	id: String!
}

input DeleteHorizonForumObjInput {
	id: String!
}

input DeleteHorizonMemberObjInput {
	id: String!
}

input DeleteHorizonObjInput {
	id: String!
}

input DeleteHorizonUpdateObjInput {
	id: String!
}

input DeletePostCommentObjInput {
	id: String!
}

input DeleteReservationObjInput {
	id: String!
}

input DeleteRetroContributionObjInput {
	id: String!
}

input DeleteRetroMemberObjInput {
	id: String!
}

input DeleteSceneIdeaObjInput {
	id: String!
}

input DeleteSpaceChapterObjInput {
	id: String!
}

input DeleteSpaceMemberObjInput {
	id: String!
}

input DeleteSpaceObjInput {
	id: String!
}

input DeleteUserObjInput {
	id: String!
}

input DeleteVerseCommentObjInput {
	id: String!
}

input DeleteVerseMemberObjInput {
	id: String!
}

type FileElem {
	id: String!
	src: String
	fileType: String
	title: String
	size: Int
	variant: String
}

input FileElemInput {
	id: String!
	src: String
	fileType: String
	title: String
	size: Int
	variant: String
}

type ForumMemberObj {
	id: String!
	forumId: String!
	userId: String!
}

type ForumMemberObjConnection {
	items: [ForumMemberObj]
	nextToken: String
}

type ForumPostObj {
	id: String!
	forumId: String!
	title: String!
	description: String!
	time: String!
}

type ForumPostObjConnection {
	items: [ForumPostObj]
	nextToken: String
}

type GalleryCollectionObj {
	id: String!
	galleryId: String!
	title: String!
	description: String!
}

type GalleryCollectionObjConnection {
	items: [GalleryCollectionObj]
	nextToken: String
}

type GalleryMemberObj {
	id: String!
	galleryId: String!
	userId: String!
}

type GalleryMemberObjConnection {
	items: [GalleryMemberObj]
	nextToken: String
}

type GalleryObj {
	id: String!
	userId: String!
	title: String!
	description: String!
	thumbnail: FileElem!
}

type GalleryObjConnection {
	items: [GalleryObj]
	nextToken: String
}

type HorizonArcObj {
	id: String!
	horizonId: String!
	userId: String!
	title: String!
	description: String!
	time: String!
}

type HorizonArcObjConnection {
	items: [HorizonArcObj]
	nextToken: String
}

type HorizonClusterObj {
	id: String!
	horizonId: String!
	parentCluster: String
	title: String!
	description: String!
	time: String!
}

type HorizonClusterObjConnection {
	items: [HorizonClusterObj]
	nextToken: String
}

type HorizonForumObj {
	id: String!
	horizonId: String!
	title: String!
	description: String!
	time: String!
}

type HorizonForumObjConnection {
	items: [HorizonForumObj]
	nextToken: String
}

type HorizonMemberObj {
	id: String!
	horizonId: String!
	userId: String!
}

type HorizonMemberObjConnection {
	items: [HorizonMemberObj]
	nextToken: String
}

type HorizonObj {
	id: String!
	userId: String!
	title: String!
	time: String!
	description: String!
	thumbnail: FileElem!
	variant: String!
}

type HorizonObjConnection {
	items: [HorizonObj]
	nextToken: String
}

type HorizonUpdateObj {
	id: String!
	horizonId: String!
	title: String!
	description: String!
	time: String!
}

type HorizonUpdateObjConnection {
	items: [HorizonUpdateObj]
	nextToken: String
}

type LinkElem {
	id: String!
	url: String
	title: String
	variant: String
}

input LinkElemInput {
	id: String!
	url: String
	title: String
	variant: String
}

type LogElem {
	id: String!
	loomId: String
	height: Int
	width: Int
	sharedUrl: String
	embedUrl: String
	variant: String
	providerUrl: String
}

input LogElemInput {
	id: String!
	loomId: String
	height: Int
	width: Int
	sharedUrl: String
	embedUrl: String
	variant: String
	providerUrl: String
}

input ModelSizeInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: [Int]
}

type NoteElem {
	id: String!
	title: String
	text: String
	variant: String
}

input NoteElemInput {
	id: String!
	title: String
	text: String
	variant: String
}

type PostCommentObj {
	id: String!
	postId: String!
	title: String!
	description: String!
	time: String!
}

type PostCommentObjConnection {
	items: [PostCommentObj]
	nextToken: String
}

type ReservationObj {
	id: String!
	fname: String!
	lname: String!
	email: String!
}

type ReservationObjConnection {
	items: [ReservationObj]
	nextToken: String
}

type RetroContributionObj {
	id: String!
	retroId: String!
	variant: String!
	ideaId: String
	conversationId: String
	sceneId: String
	verseId: String
	value: Int!
	message: String!
	time: String!
}

type RetroContributionObjConnection {
	items: [RetroContributionObj]
	nextToken: String
}

type RetroMemberObj {
	id: String!
	retroId: String!
	userId: String!
}

type RetroMemberObjConnection {
	items: [RetroMemberObj]
	nextToken: String
}

type SceneIdeaObj {
	id: String!
	userId: String!
	sceneId: String!
	title: String!
	description: String!
	x: Int!
	y: Int!
	variant: String!
	file: FileElem
	log: LogElem
	note: NoteElem
	link: LinkElem
	score: ScoreElem
}

type SceneIdeaObjConnection {
	items: [SceneIdeaObj]
	nextToken: String
}

type ScoreElem {
	id: String!
	title: String
	variant: String
}

input ScoreElemInput {
	id: String!
	title: String
	variant: String
}

type SpaceChapterObj {
	id: String!
	spaceId: String!
	title: String!
	description: String!
	idx: Int!
}

type SpaceChapterObjConnection {
	items: [SpaceChapterObj]
	nextToken: String
}

type SpaceMemberObj {
	id: String!
	spaceId: String!
	userId: String!
}

type SpaceMemberObjConnection {
	items: [SpaceMemberObj]
	nextToken: String
}

type SpaceObj {
	id: String!
	userId: String!
	title: String!
	time: String!
	description: String!
	thumbnail: FileElem!
	variant: String!
}

type SpaceObjConnection {
	items: [SpaceObj]
	nextToken: String
}

input TableArcPointObjFilterInput {
	id: TableStringFilterInput
	arcId: TableStringFilterInput
	userId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableBooleanFilterInput {
	ne: Boolean
	eq: Boolean
	attributeExists: Boolean
}

input TableChapterChatObjFilterInput {
	id: TableStringFilterInput
	chapterId: TableStringFilterInput
	title: TableStringFilterInput
	summary: TableStringFilterInput
	time: TableStringFilterInput
}

input TableChapterRetroObjFilterInput {
	id: TableStringFilterInput
	chapterId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableChapterSceneObjFilterInput {
	id: TableStringFilterInput
	chapterId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	variant: TableStringFilterInput
}

input TableChapterVerseObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	chapterId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableChatConversationObjFilterInput {
	id: TableStringFilterInput
	chatId: TableStringFilterInput
	summary: TableStringFilterInput
	time: TableStringFilterInput
}

input TableChatMemberObjFilterInput {
	id: TableStringFilterInput
	chatId: TableStringFilterInput
	variant: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableClusterMemberObjFilterInput {
	id: TableStringFilterInput
	clusterId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableClusterUpdateObjFilterInput {
	id: TableStringFilterInput
	clusterId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableCollectionResourceObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	collectionId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	variant: TableStringFilterInput
}

input TableConversationMessageObjFilterInput {
	id: TableStringFilterInput
	memberId: TableStringFilterInput
	conversationId: TableStringFilterInput
	time: TableStringFilterInput
	message: TableStringFilterInput
}

input TableFloatFilterInput {
	ne: Float
	eq: Float
	le: Float
	lt: Float
	ge: Float
	gt: Float
	between: [Float]
	attributeExists: Boolean
}

input TableForumMemberObjFilterInput {
	id: TableStringFilterInput
	forumId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableForumPostObjFilterInput {
	id: TableStringFilterInput
	forumId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableGalleryCollectionObjFilterInput {
	id: TableStringFilterInput
	galleryId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
}

input TableGalleryMemberObjFilterInput {
	id: TableStringFilterInput
	galleryId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableGalleryObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
}

input TableHorizonArcObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	horizonId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableHorizonClusterObjFilterInput {
	id: TableStringFilterInput
	horizonId: TableStringFilterInput
	parentCluster: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableHorizonForumObjFilterInput {
	id: TableStringFilterInput
	horizonId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableHorizonMemberObjFilterInput {
	id: TableStringFilterInput
	horizonId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableHorizonObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	title: TableStringFilterInput
	time: TableStringFilterInput
	description: TableStringFilterInput
	variant: TableStringFilterInput
}

input TableHorizonUpdateObjFilterInput {
	id: TableStringFilterInput
	horizonId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableIDFilterInput {
	ne: ID
	eq: ID
	le: ID
	lt: ID
	ge: ID
	gt: ID
	contains: ID
	notContains: ID
	between: [ID]
	beginsWith: ID
	attributeExists: Boolean
	size: ModelSizeInput
}

input TableIntFilterInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	between: [Int]
	attributeExists: Boolean
}

input TablePostCommentObjFilterInput {
	id: TableStringFilterInput
	postId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	time: TableStringFilterInput
}

input TableReservationObjFilterInput {
	id: TableStringFilterInput
	fname: TableStringFilterInput
	lname: TableStringFilterInput
	email: TableStringFilterInput
}

input TableRetroContributionObjFilterInput {
	id: TableStringFilterInput
	retroId: TableStringFilterInput
	variant: TableStringFilterInput
	conversationId: TableStringFilterInput
	ideaId: TableStringFilterInput
	sceneId: TableStringFilterInput
	verseId: TableStringFilterInput
	value: TableIntFilterInput
	message: TableStringFilterInput
	time: TableStringFilterInput
}

input TableRetroMemberObjFilterInput {
	id: TableStringFilterInput
	retroId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableSceneIdeaObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	sceneId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	x: TableIntFilterInput
	y: TableIntFilterInput
	variant: TableStringFilterInput
}

input TableSpaceChapterObjFilterInput {
	id: TableStringFilterInput
	spaceId: TableStringFilterInput
	title: TableStringFilterInput
	description: TableStringFilterInput
	idx: TableIntFilterInput
}

input TableSpaceMemberObjFilterInput {
	id: TableStringFilterInput
	spaceId: TableStringFilterInput
	userId: TableStringFilterInput
}

input TableSpaceObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	title: TableStringFilterInput
	time: TableStringFilterInput
	description: TableStringFilterInput
	variant: TableStringFilterInput
}

input TableStringFilterInput {
	ne: String
	eq: String
	le: String
	lt: String
	ge: String
	gt: String
	contains: String
	notContains: String
	between: [String]
	beginsWith: String
	attributeExists: Boolean
	size: ModelSizeInput
}

input TableUserObjFilterInput {
	id: TableStringFilterInput
	fname: TableStringFilterInput
	lname: TableStringFilterInput
	passwordHash: TableStringFilterInput
	email: TableStringFilterInput
	googleId: TableStringFilterInput
	customerId: TableStringFilterInput
	subscriptionId: TableStringFilterInput
	priceId: TableStringFilterInput
	created: TableStringFilterInput
}

input TableVerseCommentObjFilterInput {
	id: TableStringFilterInput
	userId: TableStringFilterInput
	verseId: TableStringFilterInput
	time: TableStringFilterInput
	message: TableStringFilterInput
}

input TableVerseMemberObjFilterInput {
	id: TableStringFilterInput
	verseId: TableStringFilterInput
	userId: TableStringFilterInput
}

input UpdateArcPointObjInput {
	id: String!
	userId: String
	arcId: String
	title: String
	description: String
	time: String
}

input UpdateChapterChatObjInput {
	id: String!
	chapterId: String
	title: String
	summary: String
	time: String
}

input UpdateChapterRetroObjInput {
	id: String!
	chapterId: String
	title: String
	description: String
	time: String
}

input UpdateChapterSceneObjInput {
	id: String!
	chapterId: String
	title: String
	description: String
	variant: String
}

input UpdateChapterVerseObjInput {
	id: String!
	userId: String
	chapterId: String
	title: String
	description: String
	time: String
}

input UpdateChatConversationObjInput {
	id: String!
	chatId: String
	summary: String
	time: String
}

input UpdateChatMemberObjInput {
	id: String!
	chatId: String
	variant: String
	userId: String
}

input UpdateClusterMemberObjInput {
	id: String!
	clusterId: String
	userId: String
}

input UpdateClusterUpdateObjInput {
	id: String!
	clusterId: String
	title: String
	description: String
	time: String
}

input UpdateCollectionResourceObjInput {
	id: String!
	userId: String
	collectionId: String
	title: String
	description: String
	variant: String
}

input UpdateConversationMessageObjInput {
	id: String!
	memberId: String
	conversationId: String
	time: String
	message: String
}

input UpdateForumMemberObjInput {
	id: String!
	forumId: String
	userId: String
}

input UpdateForumPostObjInput {
	id: String!
	forumId: String
	title: String
	description: String
	time: String
}

input UpdateGalleryCollectionObjInput {
	id: String!
	galleryId: String
	title: String
	description: String
}

input UpdateGalleryMemberObjInput {
	id: String!
	galleryId: String
	userId: String
}

input UpdateGalleryObjInput {
	id: String!
	userId: String
	title: String
	description: String
	thumbnail: FileElemInput
}

input UpdateHorizonArcObjInput {
	id: String!
	userId: String
	horizonId: String
	title: String
	description: String
	time: String
}

input UpdateHorizonClusterObjInput {
	id: String!
	horizonId: String
	parentCluster: String
	title: String
	description: String
	time: String
}

input UpdateHorizonForumObjInput {
	id: String!
	horizonId: String
	title: String
	description: String
	time: String
}

input UpdateHorizonMemberObjInput {
	id: String!
	horizonId: String
	userId: String
}

input UpdateHorizonObjInput {
	id: String!
	userId: String
	title: String
	time: String
	description: String
	variant: String
	thumbnail: FileElemInput
}

input UpdateHorizonUpdateObjInput {
	id: String!
	horizonId: String
	title: String
	description: String
	time: String
}

input UpdatePostCommentObjInput {
	id: String!
	postId: String
	title: String
	description: String
	time: String
}

input UpdateReservationObjInput {
	id: String!
	fname: String
	lname: String
	email: String
}

input UpdateRetroContributionObjInput {
	id: String!
	retroId: String
	variant: String
	conversationId: String
	ideaId: String
	sceneId: String
	verseId: String
	value: Int
	message: String
	time: String
}

input UpdateRetroMemberObjInput {
	id: String!
	retroId: String
	userId: String
}

input UpdateSceneIdeaObjInput {
	id: String!
	userId: String
	sceneId: String
	title: String
	description: String
	x: Int
	y: Int
	variant: String
	file: FileElemInput
	log: LogElemInput
	note: NoteElemInput
	link: LinkElemInput
	score: ScoreElemInput
}

input UpdateSpaceChapterObjInput {
	id: String!
	spaceId: String
	title: String
	description: String
	idx: Int
	thumbnail: FileElemInput
}

input UpdateSpaceMemberObjInput {
	id: String!
	spaceId: String
	userId: String
}

input UpdateSpaceObjInput {
	id: String!
	userId: String
	title: String
	time: String
	description: String
	variant: String
}

input UpdateUserObjInput {
	id: String!
	fname: String
	lname: String
	passwordHash: String
	email: String
	googleId: String
	customerId: String
	subscriptionId: String
	priceId: String
	created: String
	profilePicture: FileElemInput
}

input UpdateVerseCommentObjInput {
	id: String!
	userId: String
	verseId: String
	time: String
	message: String
}

input UpdateVerseMemberObjInput {
	id: String!
	verseId: String
	userId: String
}

type UserObj {
	id: String!
	fname: String!
	lname: String!
	passwordHash: String
	email: String!
	googleId: String
	profilePicture: FileElem
	customerId: String
	subscriptionId: String
	priceId: String
	created: String!
}

type UserObjConnection {
	items: [UserObj]
	nextToken: String
}

type VerseCommentObj {
	id: String!
	userId: String!
	verseId: String!
	time: String!
	message: String!
}

type VerseCommentObjConnection {
	items: [VerseCommentObj]
	nextToken: String
}

type VerseMemberObj {
	id: String!
	verseId: String!
	userId: String!
}

type VerseMemberObjConnection {
	items: [VerseMemberObj]
	nextToken: String
}

type Mutation {
	createChapterSceneObj(input: CreateChapterSceneObjInput!): ChapterSceneObj
	updateChapterSceneObj(input: UpdateChapterSceneObjInput!): ChapterSceneObj
	deleteChapterSceneObj(input: DeleteChapterSceneObjInput!): ChapterSceneObj
	createHorizonClusterObj(input: CreateHorizonClusterObjInput!): HorizonClusterObj
	updateHorizonClusterObj(input: UpdateHorizonClusterObjInput!): HorizonClusterObj
	deleteHorizonClusterObj(input: DeleteHorizonClusterObjInput!): HorizonClusterObj
	createArcPointObj(input: CreateArcPointObjInput!): ArcPointObj
	updateArcPointObj(input: UpdateArcPointObjInput!): ArcPointObj
	deleteArcPointObj(input: DeleteArcPointObjInput!): ArcPointObj
	createConversationMessageObj(input: CreateConversationMessageObjInput!): ConversationMessageObj
	updateConversationMessageObj(input: UpdateConversationMessageObjInput!): ConversationMessageObj
	deleteConversationMessageObj(input: DeleteConversationMessageObjInput!): ConversationMessageObj
	createChatConversationObj(input: CreateChatConversationObjInput!): ChatConversationObj
	updateChatConversationObj(input: UpdateChatConversationObjInput!): ChatConversationObj
	deleteChatConversationObj(input: DeleteChatConversationObjInput!): ChatConversationObj
	createSceneIdeaObj(input: CreateSceneIdeaObjInput!): SceneIdeaObj
	updateSceneIdeaObj(input: UpdateSceneIdeaObjInput!): SceneIdeaObj
	deleteSceneIdeaObj(input: DeleteSceneIdeaObjInput!): SceneIdeaObj
	createClusterUpdateObj(input: CreateClusterUpdateObjInput!): ClusterUpdateObj
	updateClusterUpdateObj(input: UpdateClusterUpdateObjInput!): ClusterUpdateObj
	deleteClusterUpdateObj(input: DeleteClusterUpdateObjInput!): ClusterUpdateObj
	createForumPostObj(input: CreateForumPostObjInput!): ForumPostObj
	updateForumPostObj(input: UpdateForumPostObjInput!): ForumPostObj
	deleteForumPostObj(input: DeleteForumPostObjInput!): ForumPostObj
	createChapterRetroObj(input: CreateChapterRetroObjInput!): ChapterRetroObj
	updateChapterRetroObj(input: UpdateChapterRetroObjInput!): ChapterRetroObj
	deleteChapterRetroObj(input: DeleteChapterRetroObjInput!): ChapterRetroObj
	createPostCommentObj(input: CreatePostCommentObjInput!): PostCommentObj
	updatePostCommentObj(input: UpdatePostCommentObjInput!): PostCommentObj
	deletePostCommentObj(input: DeletePostCommentObjInput!): PostCommentObj
	createHorizonArcObj(input: CreateHorizonArcObjInput!): HorizonArcObj
	updateHorizonArcObj(input: UpdateHorizonArcObjInput!): HorizonArcObj
	deleteHorizonArcObj(input: DeleteHorizonArcObjInput!): HorizonArcObj
	createChapterChatObj(input: CreateChapterChatObjInput!): ChapterChatObj
	updateChapterChatObj(input: UpdateChapterChatObjInput!): ChapterChatObj
	deleteChapterChatObj(input: DeleteChapterChatObjInput!): ChapterChatObj
	createHorizonObj(input: CreateHorizonObjInput!): HorizonObj
	updateHorizonObj(input: UpdateHorizonObjInput!): HorizonObj
	deleteHorizonObj(input: DeleteHorizonObjInput!): HorizonObj
	createCollectionResourceObj(input: CreateCollectionResourceObjInput!): CollectionResourceObj
	updateCollectionResourceObj(input: UpdateCollectionResourceObjInput!): CollectionResourceObj
	deleteCollectionResourceObj(input: DeleteCollectionResourceObjInput!): CollectionResourceObj
	createUserObj(input: CreateUserObjInput!): UserObj
	updateUserObj(input: UpdateUserObjInput!): UserObj
	deleteUserObj(input: DeleteUserObjInput!): UserObj
	createVerseCommentObj(input: CreateVerseCommentObjInput!): VerseCommentObj
	updateVerseCommentObj(input: UpdateVerseCommentObjInput!): VerseCommentObj
	deleteVerseCommentObj(input: DeleteVerseCommentObjInput!): VerseCommentObj
	createGalleryCollectionObj(input: CreateGalleryCollectionObjInput!): GalleryCollectionObj
	updateGalleryCollectionObj(input: UpdateGalleryCollectionObjInput!): GalleryCollectionObj
	deleteGalleryCollectionObj(input: DeleteGalleryCollectionObjInput!): GalleryCollectionObj
	createSpaceChapterObj(input: CreateSpaceChapterObjInput!): SpaceChapterObj
	updateSpaceChapterObj(input: UpdateSpaceChapterObjInput!): SpaceChapterObj
	deleteSpaceChapterObj(input: DeleteSpaceChapterObjInput!): SpaceChapterObj
	createRetroContributionObj(input: CreateRetroContributionObjInput!): RetroContributionObj
	updateRetroContributionObj(input: UpdateRetroContributionObjInput!): RetroContributionObj
	deleteRetroContributionObj(input: DeleteRetroContributionObjInput!): RetroContributionObj
	createHorizonForumObj(input: CreateHorizonForumObjInput!): HorizonForumObj
	updateHorizonForumObj(input: UpdateHorizonForumObjInput!): HorizonForumObj
	deleteHorizonForumObj(input: DeleteHorizonForumObjInput!): HorizonForumObj
	createReservationObj(input: CreateReservationObjInput!): ReservationObj
	updateReservationObj(input: UpdateReservationObjInput!): ReservationObj
	deleteReservationObj(input: DeleteReservationObjInput!): ReservationObj
	createChapterVerseObj(input: CreateChapterVerseObjInput!): ChapterVerseObj
	updateChapterVerseObj(input: UpdateChapterVerseObjInput!): ChapterVerseObj
	deleteChapterVerseObj(input: DeleteChapterVerseObjInput!): ChapterVerseObj
	createGalleryObj(input: CreateGalleryObjInput!): GalleryObj
	updateGalleryObj(input: UpdateGalleryObjInput!): GalleryObj
	deleteGalleryObj(input: DeleteGalleryObjInput!): GalleryObj
	createSpaceObj(input: CreateSpaceObjInput!): SpaceObj
	updateSpaceObj(input: UpdateSpaceObjInput!): SpaceObj
	deleteSpaceObj(input: DeleteSpaceObjInput!): SpaceObj
	createChatMemberObj(input: CreateChatMemberObjInput!): ChatMemberObj
	updateChatMemberObj(input: UpdateChatMemberObjInput!): ChatMemberObj
	deleteChatMemberObj(input: DeleteChatMemberObjInput!): ChatMemberObj
	createHorizonUpdateObj(input: CreateHorizonUpdateObjInput!): HorizonUpdateObj
	updateHorizonUpdateObj(input: UpdateHorizonUpdateObjInput!): HorizonUpdateObj
	deleteHorizonUpdateObj(input: DeleteHorizonUpdateObjInput!): HorizonUpdateObj
	createClusterMemberObj(input: CreateClusterMemberObjInput!): ClusterMemberObj
	updateClusterMemberObj(input: UpdateClusterMemberObjInput!): ClusterMemberObj
	deleteClusterMemberObj(input: DeleteClusterMemberObjInput!): ClusterMemberObj
	createForumMemberObj(input: CreateForumMemberObjInput!): ForumMemberObj
	updateForumMemberObj(input: UpdateForumMemberObjInput!): ForumMemberObj
	deleteForumMemberObj(input: DeleteForumMemberObjInput!): ForumMemberObj
	createHorizonMemberObj(input: CreateHorizonMemberObjInput!): HorizonMemberObj
	updateHorizonMemberObj(input: UpdateHorizonMemberObjInput!): HorizonMemberObj
	deleteHorizonMemberObj(input: DeleteHorizonMemberObjInput!): HorizonMemberObj
	createSpaceMemberObj(input: CreateSpaceMemberObjInput!): SpaceMemberObj
	updateSpaceMemberObj(input: UpdateSpaceMemberObjInput!): SpaceMemberObj
	deleteSpaceMemberObj(input: DeleteSpaceMemberObjInput!): SpaceMemberObj
	createGalleryMemberObj(input: CreateGalleryMemberObjInput!): GalleryMemberObj
	updateGalleryMemberObj(input: UpdateGalleryMemberObjInput!): GalleryMemberObj
	deleteGalleryMemberObj(input: DeleteGalleryMemberObjInput!): GalleryMemberObj
	createVerseMemberObj(input: CreateVerseMemberObjInput!): VerseMemberObj
	updateVerseMemberObj(input: UpdateVerseMemberObjInput!): VerseMemberObj
	deleteVerseMemberObj(input: DeleteVerseMemberObjInput!): VerseMemberObj
	createRetroMemberObj(input: CreateRetroMemberObjInput!): RetroMemberObj
	updateRetroMemberObj(input: UpdateRetroMemberObjInput!): RetroMemberObj
	deleteRetroMemberObj(input: DeleteRetroMemberObjInput!): RetroMemberObj
}

type Query {
	getUser: UserObj
	getChapterSceneObj(id: String!): ChapterSceneObj
	listChapterSceneObjs(filter: TableChapterSceneObjFilterInput, limit: Int, nextToken: String): ChapterSceneObjConnection
	getHorizonClusterObj(id: String!): HorizonClusterObj
	listHorizonClusterObjs(filter: TableHorizonClusterObjFilterInput, limit: Int, nextToken: String): HorizonClusterObjConnection
	getArcPointObj(id: String!): ArcPointObj
	listArcPointObjs(filter: TableArcPointObjFilterInput, limit: Int, nextToken: String): ArcPointObjConnection
	getConversationMessageObj(id: String!): ConversationMessageObj
	listConversationMessageObjs(filter: TableConversationMessageObjFilterInput, limit: Int, nextToken: String): ConversationMessageObjConnection
	getChatConversationObj(id: String!): ChatConversationObj
	listChatConversationObjs(filter: TableChatConversationObjFilterInput, limit: Int, nextToken: String): ChatConversationObjConnection
	getSceneIdeaObj(id: String!): SceneIdeaObj
	listSceneIdeaObjs(filter: TableSceneIdeaObjFilterInput, limit: Int, nextToken: String): SceneIdeaObjConnection
	getClusterUpdateObj(id: String!): ClusterUpdateObj
	listClusterUpdateObjs(filter: TableClusterUpdateObjFilterInput, limit: Int, nextToken: String): ClusterUpdateObjConnection
	getForumPostObj(id: String!): ForumPostObj
	listForumPostObjs(filter: TableForumPostObjFilterInput, limit: Int, nextToken: String): ForumPostObjConnection
	getChapterRetroObj(id: String!): ChapterRetroObj
	listChapterRetroObjs(filter: TableChapterRetroObjFilterInput, limit: Int, nextToken: String): ChapterRetroObjConnection
	getPostCommentObj(id: String!): PostCommentObj
	listPostCommentObjs(filter: TablePostCommentObjFilterInput, limit: Int, nextToken: String): PostCommentObjConnection
	getHorizonArcObj(id: String!): HorizonArcObj
	listHorizonArcObjs(filter: TableHorizonArcObjFilterInput, limit: Int, nextToken: String): HorizonArcObjConnection
	getChapterChatObj(id: String!): ChapterChatObj
	listChapterChatObjs(filter: TableChapterChatObjFilterInput, limit: Int, nextToken: String): ChapterChatObjConnection
	getHorizonObj(id: String!): HorizonObj
	listHorizonObjs(filter: TableHorizonObjFilterInput, limit: Int, nextToken: String): HorizonObjConnection
	getCollectionResourceObj(id: String!): CollectionResourceObj
	listCollectionResourceObjs(filter: TableCollectionResourceObjFilterInput, limit: Int, nextToken: String): CollectionResourceObjConnection
	getUserObj(id: String!): UserObj
	listUserObjs(filter: TableUserObjFilterInput, limit: Int, nextToken: String): UserObjConnection
	getVerseCommentObj(id: String!): VerseCommentObj
	listVerseCommentObjs(filter: TableVerseCommentObjFilterInput, limit: Int, nextToken: String): VerseCommentObjConnection
	getGalleryCollectionObj(id: String!): GalleryCollectionObj
	listGalleryCollectionObjs(filter: TableGalleryCollectionObjFilterInput, limit: Int, nextToken: String): GalleryCollectionObjConnection
	getSpaceChapterObj(id: String!): SpaceChapterObj
	listSpaceChapterObjs(filter: TableSpaceChapterObjFilterInput, limit: Int, nextToken: String): SpaceChapterObjConnection
	getRetroContributionObj(id: String!): RetroContributionObj
	listRetroContributionObjs(filter: TableRetroContributionObjFilterInput, limit: Int, nextToken: String): RetroContributionObjConnection
	getHorizonForumObj(id: String!): HorizonForumObj
	listHorizonForumObjs(filter: TableHorizonForumObjFilterInput, limit: Int, nextToken: String): HorizonForumObjConnection
	getReservationObj(id: String!): ReservationObj
	listReservationObjs(filter: TableReservationObjFilterInput, limit: Int, nextToken: String): ReservationObjConnection
	getChapterVerseObj(id: String!): ChapterVerseObj
	listChapterVerseObjs(filter: TableChapterVerseObjFilterInput, limit: Int, nextToken: String): ChapterVerseObjConnection
	getGalleryObj(id: String!): GalleryObj
	listGalleryObjs(filter: TableGalleryObjFilterInput, limit: Int, nextToken: String): GalleryObjConnection
	getSpaceObj(id: String!): SpaceObj
	listSpaceObjs(filter: TableSpaceObjFilterInput, limit: Int, nextToken: String): SpaceObjConnection
	getChatMemberObj(id: String!): ChatMemberObj
	listChatMemberObjs(filter: TableChatMemberObjFilterInput, limit: Int, nextToken: String): ChatMemberObjConnection
	getHorizonUpdateObj(id: String!): HorizonUpdateObj
	listHorizonUpdateObjs(filter: TableHorizonUpdateObjFilterInput, limit: Int, nextToken: String): HorizonUpdateObjConnection
	getClusterMemberObj(id: String!): ClusterMemberObj
	listClusterMemberObjs(filter: TableClusterMemberObjFilterInput, limit: Int, nextToken: String): ClusterMemberObjConnection
	getForumMemberObj(id: String!): ForumMemberObj
	listForumMemberObjs(filter: TableForumMemberObjFilterInput, limit: Int, nextToken: String): ForumMemberObjConnection
	getHorizonMemberObj(id: String!): HorizonMemberObj
	listHorizonMemberObjs(filter: TableHorizonMemberObjFilterInput, limit: Int, nextToken: String): HorizonMemberObjConnection
	getSpaceMemberObj(id: String!): SpaceMemberObj
	listSpaceMemberObjs(filter: TableSpaceMemberObjFilterInput, limit: Int, nextToken: String): SpaceMemberObjConnection
	getGalleryMemberObj(id: String!): GalleryMemberObj
	listGalleryMemberObjs(filter: TableGalleryMemberObjFilterInput, limit: Int, nextToken: String): GalleryMemberObjConnection
	getVerseMemberObj(id: String!): VerseMemberObj
	listVerseMemberObjs(filter: TableVerseMemberObjFilterInput, limit: Int, nextToken: String): VerseMemberObjConnection
	getRetroMemberObj(id: String!): RetroMemberObj
	listRetroMemberObjs(filter: TableRetroMemberObjFilterInput, limit: Int, nextToken: String): RetroMemberObjConnection
}

type Subscription {
	onCreateChapterSceneObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		variant: String
	): ChapterSceneObj
		@aws_subscribe(mutations: ["createChapterSceneObj"])
	onUpdateChapterSceneObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		variant: String
	): ChapterSceneObj
		@aws_subscribe(mutations: ["updateChapterSceneObj"])
	onDeleteChapterSceneObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		variant: String
	): ChapterSceneObj
		@aws_subscribe(mutations: ["deleteChapterSceneObj"])
	onCreateHorizonClusterObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonClusterObj
		@aws_subscribe(mutations: ["createHorizonClusterObj"])
	onUpdateHorizonClusterObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonClusterObj
		@aws_subscribe(mutations: ["updateHorizonClusterObj"])
	onDeleteHorizonClusterObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonClusterObj
		@aws_subscribe(mutations: ["deleteHorizonClusterObj"])
	onCreateArcPointObj(
		id: String,
		arcId: String,
		title: String,
		description: String,
		time: String
	): ArcPointObj
		@aws_subscribe(mutations: ["createArcPointObj"])
	onUpdateArcPointObj(
		id: String,
		arcId: String,
		title: String,
		description: String,
		time: String
	): ArcPointObj
		@aws_subscribe(mutations: ["updateArcPointObj"])
	onDeleteArcPointObj(
		id: String,
		arcId: String,
		title: String,
		description: String,
		time: String
	): ArcPointObj
		@aws_subscribe(mutations: ["deleteArcPointObj"])
	onCreateConversationMessageObj(
		id: String,
		memberId: String,
		conversationId: String,
		time: String
	): ConversationMessageObj
		@aws_subscribe(mutations: ["createConversationMessageObj"])
	onUpdateConversationMessageObj(
		id: String,
		memberId: String,
		conversationId: String,
		time: String
	): ConversationMessageObj
		@aws_subscribe(mutations: ["updateConversationMessageObj"])
	onDeleteConversationMessageObj(
		id: String,
		memberId: String,
		conversationId: String,
		time: String
	): ConversationMessageObj
		@aws_subscribe(mutations: ["deleteConversationMessageObj"])
	onCreateChatConversationObj(
		id: String,
		chatId: String,
		summary: String,
		time: String
	): ChatConversationObj
		@aws_subscribe(mutations: ["createChatConversationObj"])
	onUpdateChatConversationObj(
		id: String,
		chatId: String,
		summary: String,
		time: String
	): ChatConversationObj
		@aws_subscribe(mutations: ["updateChatConversationObj"])
	onDeleteChatConversationObj(
		id: String,
		chatId: String,
		summary: String,
		time: String
	): ChatConversationObj
		@aws_subscribe(mutations: ["deleteChatConversationObj"])
	onCreateSceneIdeaObj(
		id: String,
		sceneId: String,
		title: String,
		description: String,
		x: Int
	): SceneIdeaObj
		@aws_subscribe(mutations: ["createSceneIdeaObj"])
	onUpdateSceneIdeaObj(
		id: String,
		sceneId: String,
		title: String,
		description: String,
		x: Int
	): SceneIdeaObj
		@aws_subscribe(mutations: ["updateSceneIdeaObj"])
	onDeleteSceneIdeaObj(
		id: String,
		sceneId: String,
		title: String,
		description: String,
		x: Int
	): SceneIdeaObj
		@aws_subscribe(mutations: ["deleteSceneIdeaObj"])
	onCreateClusterUpdateObj(
		id: String,
		clusterId: String,
		title: String,
		description: String,
		time: String
	): ClusterUpdateObj
		@aws_subscribe(mutations: ["createClusterUpdateObj"])
	onUpdateClusterUpdateObj(
		id: String,
		clusterId: String,
		title: String,
		description: String,
		time: String
	): ClusterUpdateObj
		@aws_subscribe(mutations: ["updateClusterUpdateObj"])
	onDeleteClusterUpdateObj(
		id: String,
		clusterId: String,
		title: String,
		description: String,
		time: String
	): ClusterUpdateObj
		@aws_subscribe(mutations: ["deleteClusterUpdateObj"])
	onCreateForumPostObj(
		id: String,
		forumId: String,
		title: String,
		description: String,
		time: String
	): ForumPostObj
		@aws_subscribe(mutations: ["createForumPostObj"])
	onUpdateForumPostObj(
		id: String,
		forumId: String,
		title: String,
		description: String,
		time: String
	): ForumPostObj
		@aws_subscribe(mutations: ["updateForumPostObj"])
	onDeleteForumPostObj(
		id: String,
		forumId: String,
		title: String,
		description: String,
		time: String
	): ForumPostObj
		@aws_subscribe(mutations: ["deleteForumPostObj"])
	onCreateChapterRetroObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterRetroObj
		@aws_subscribe(mutations: ["createChapterRetroObj"])
	onUpdateChapterRetroObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterRetroObj
		@aws_subscribe(mutations: ["updateChapterRetroObj"])
	onDeleteChapterRetroObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterRetroObj
		@aws_subscribe(mutations: ["deleteChapterRetroObj"])
	onCreatePostCommentObj(
		id: String,
		postId: String,
		title: String,
		description: String,
		time: String
	): PostCommentObj
		@aws_subscribe(mutations: ["createPostCommentObj"])
	onUpdatePostCommentObj(
		id: String,
		postId: String,
		title: String,
		description: String,
		time: String
	): PostCommentObj
		@aws_subscribe(mutations: ["updatePostCommentObj"])
	onDeletePostCommentObj(
		id: String,
		postId: String,
		title: String,
		description: String,
		time: String
	): PostCommentObj
		@aws_subscribe(mutations: ["deletePostCommentObj"])
	onCreateHorizonArcObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonArcObj
		@aws_subscribe(mutations: ["createHorizonArcObj"])
	onUpdateHorizonArcObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonArcObj
		@aws_subscribe(mutations: ["updateHorizonArcObj"])
	onDeleteHorizonArcObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonArcObj
		@aws_subscribe(mutations: ["deleteHorizonArcObj"])
	onCreateChapterChatObj(
		id: String,
		chapterId: String,
		title: String,
		summary: String,
		time: String
	): ChapterChatObj
		@aws_subscribe(mutations: ["createChapterChatObj"])
	onUpdateChapterChatObj(
		id: String,
		chapterId: String,
		title: String,
		summary: String,
		time: String
	): ChapterChatObj
		@aws_subscribe(mutations: ["updateChapterChatObj"])
	onDeleteChapterChatObj(
		id: String,
		chapterId: String,
		title: String,
		summary: String,
		time: String
	): ChapterChatObj
		@aws_subscribe(mutations: ["deleteChapterChatObj"])
	onCreateHorizonObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): HorizonObj
		@aws_subscribe(mutations: ["createHorizonObj"])
	onUpdateHorizonObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): HorizonObj
		@aws_subscribe(mutations: ["updateHorizonObj"])
	onDeleteHorizonObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): HorizonObj
		@aws_subscribe(mutations: ["deleteHorizonObj"])
	onCreateCollectionResourceObj(
		id: String,
		userId: String,
		collectionId: String,
		title: String,
		description: String
	): CollectionResourceObj
		@aws_subscribe(mutations: ["createCollectionResourceObj"])
	onUpdateCollectionResourceObj(
		id: String,
		userId: String,
		collectionId: String,
		title: String,
		description: String
	): CollectionResourceObj
		@aws_subscribe(mutations: ["updateCollectionResourceObj"])
	onDeleteCollectionResourceObj(
		id: String,
		userId: String,
		collectionId: String,
		title: String,
		description: String
	): CollectionResourceObj
		@aws_subscribe(mutations: ["deleteCollectionResourceObj"])
	onCreateUserObj(
		id: String,
		fname: String,
		lname: String,
		passwordHash: String,
		email: String
	): UserObj
		@aws_subscribe(mutations: ["createUserObj"])
	onUpdateUserObj(
		id: String,
		fname: String,
		lname: String,
		passwordHash: String,
		email: String
	): UserObj
		@aws_subscribe(mutations: ["updateUserObj"])
	onDeleteUserObj(
		id: String,
		fname: String,
		lname: String,
		passwordHash: String,
		email: String
	): UserObj
		@aws_subscribe(mutations: ["deleteUserObj"])
	onCreateVerseCommentObj(
		id: String,
		userId: String,
		verseId: String,
		time: String
	): VerseCommentObj
		@aws_subscribe(mutations: ["createVerseCommentObj"])
	onUpdateVerseCommentObj(
		id: String,
		userId: String,
		verseId: String,
		time: String
	): VerseCommentObj
		@aws_subscribe(mutations: ["updateVerseCommentObj"])
	onDeleteVerseCommentObj(
		id: String,
		userId: String,
		verseId: String,
		time: String
	): VerseCommentObj
		@aws_subscribe(mutations: ["deleteVerseCommentObj"])
	onCreateGalleryCollectionObj(
		id: String,
		galleryId: String,
		title: String,
		description: String
	): GalleryCollectionObj
		@aws_subscribe(mutations: ["createGalleryCollectionObj"])
	onUpdateGalleryCollectionObj(
		id: String,
		galleryId: String,
		title: String,
		description: String
	): GalleryCollectionObj
		@aws_subscribe(mutations: ["updateGalleryCollectionObj"])
	onDeleteGalleryCollectionObj(
		id: String,
		galleryId: String,
		title: String,
		description: String
	): GalleryCollectionObj
		@aws_subscribe(mutations: ["deleteGalleryCollectionObj"])
	onCreateSpaceChapterObj(
		id: String,
		spaceId: String,
		title: String,
		description: String,
		idx: Int
	): SpaceChapterObj
		@aws_subscribe(mutations: ["createSpaceChapterObj"])
	onUpdateSpaceChapterObj(
		id: String,
		spaceId: String,
		title: String,
		description: String,
		idx: Int
	): SpaceChapterObj
		@aws_subscribe(mutations: ["updateSpaceChapterObj"])
	onDeleteSpaceChapterObj(
		id: String,
		spaceId: String,
		title: String,
		description: String,
		idx: Int
	): SpaceChapterObj
		@aws_subscribe(mutations: ["deleteSpaceChapterObj"])
	onCreateRetroContributionObj(
		id: String,
		retroId: String,
		variant: String,
		conversationId: String,
		sceneId: String
	): RetroContributionObj
		@aws_subscribe(mutations: ["createRetroContributionObj"])
	onUpdateRetroContributionObj(
		id: String,
		retroId: String,
		variant: String,
		conversationId: String,
		sceneId: String
	): RetroContributionObj
		@aws_subscribe(mutations: ["updateRetroContributionObj"])
	onDeleteRetroContributionObj(
		id: String,
		retroId: String,
		variant: String,
		conversationId: String,
		sceneId: String
	): RetroContributionObj
		@aws_subscribe(mutations: ["deleteRetroContributionObj"])
	onCreateHorizonForumObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonForumObj
		@aws_subscribe(mutations: ["createHorizonForumObj"])
	onUpdateHorizonForumObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonForumObj
		@aws_subscribe(mutations: ["updateHorizonForumObj"])
	onDeleteHorizonForumObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonForumObj
		@aws_subscribe(mutations: ["deleteHorizonForumObj"])
	onCreateReservationObj(
		id: String,
		fname: String,
		lname: String,
		email: String
	): ReservationObj
		@aws_subscribe(mutations: ["createReservationObj"])
	onUpdateReservationObj(
		id: String,
		fname: String,
		lname: String,
		email: String
	): ReservationObj
		@aws_subscribe(mutations: ["updateReservationObj"])
	onDeleteReservationObj(
		id: String,
		fname: String,
		lname: String,
		email: String
	): ReservationObj
		@aws_subscribe(mutations: ["deleteReservationObj"])
	onCreateChapterVerseObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterVerseObj
		@aws_subscribe(mutations: ["createChapterVerseObj"])
	onUpdateChapterVerseObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterVerseObj
		@aws_subscribe(mutations: ["updateChapterVerseObj"])
	onDeleteChapterVerseObj(
		id: String,
		chapterId: String,
		title: String,
		description: String,
		time: String
	): ChapterVerseObj
		@aws_subscribe(mutations: ["deleteChapterVerseObj"])
	onCreateGalleryObj(
		id: String,
		userId: String,
		title: String,
		description: String
	): GalleryObj
		@aws_subscribe(mutations: ["createGalleryObj"])
	onUpdateGalleryObj(
		id: String,
		userId: String,
		title: String,
		description: String
	): GalleryObj
		@aws_subscribe(mutations: ["updateGalleryObj"])
	onDeleteGalleryObj(
		id: String,
		userId: String,
		title: String,
		description: String
	): GalleryObj
		@aws_subscribe(mutations: ["deleteGalleryObj"])
	onCreateSpaceObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): SpaceObj
		@aws_subscribe(mutations: ["createSpaceObj"])
	onUpdateSpaceObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): SpaceObj
		@aws_subscribe(mutations: ["updateSpaceObj"])
	onDeleteSpaceObj(
		id: String,
		userId: String,
		title: String,
		time: String,
		description: String
	): SpaceObj
		@aws_subscribe(mutations: ["deleteSpaceObj"])
	onCreateChatMemberObj(
		id: String,
		chatId: String,
		variant: String,
		userId: String
	): ChatMemberObj
		@aws_subscribe(mutations: ["createChatMemberObj"])
	onUpdateChatMemberObj(
		id: String,
		chatId: String,
		variant: String,
		userId: String
	): ChatMemberObj
		@aws_subscribe(mutations: ["updateChatMemberObj"])
	onDeleteChatMemberObj(
		id: String,
		chatId: String,
		variant: String,
		userId: String
	): ChatMemberObj
		@aws_subscribe(mutations: ["deleteChatMemberObj"])
	onCreateHorizonUpdateObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonUpdateObj
		@aws_subscribe(mutations: ["createHorizonUpdateObj"])
	onUpdateHorizonUpdateObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonUpdateObj
		@aws_subscribe(mutations: ["updateHorizonUpdateObj"])
	onDeleteHorizonUpdateObj(
		id: String,
		horizonId: String,
		title: String,
		description: String,
		time: String
	): HorizonUpdateObj
		@aws_subscribe(mutations: ["deleteHorizonUpdateObj"])
	onCreateClusterMemberObj(id: String, clusterId: String, userId: String): ClusterMemberObj
		@aws_subscribe(mutations: ["createClusterMemberObj"])
	onUpdateClusterMemberObj(id: String, clusterId: String, userId: String): ClusterMemberObj
		@aws_subscribe(mutations: ["updateClusterMemberObj"])
	onDeleteClusterMemberObj(id: String, clusterId: String, userId: String): ClusterMemberObj
		@aws_subscribe(mutations: ["deleteClusterMemberObj"])
	onCreateForumMemberObj(id: String, forumId: String, userId: String): ForumMemberObj
		@aws_subscribe(mutations: ["createForumMemberObj"])
	onUpdateForumMemberObj(id: String, forumId: String, userId: String): ForumMemberObj
		@aws_subscribe(mutations: ["updateForumMemberObj"])
	onDeleteForumMemberObj(id: String, forumId: String, userId: String): ForumMemberObj
		@aws_subscribe(mutations: ["deleteForumMemberObj"])
	onCreateHorizonMemberObj(id: String, horizonId: String, userId: String): HorizonMemberObj
		@aws_subscribe(mutations: ["createHorizonMemberObj"])
	onUpdateHorizonMemberObj(id: String, horizonId: String, userId: String): HorizonMemberObj
		@aws_subscribe(mutations: ["updateHorizonMemberObj"])
	onDeleteHorizonMemberObj(id: String, horizonId: String, userId: String): HorizonMemberObj
		@aws_subscribe(mutations: ["deleteHorizonMemberObj"])
	onCreateSpaceMemberObj(id: String, spaceId: String, userId: String): SpaceMemberObj
		@aws_subscribe(mutations: ["createSpaceMemberObj"])
	onUpdateSpaceMemberObj(id: String, spaceId: String, userId: String): SpaceMemberObj
		@aws_subscribe(mutations: ["updateSpaceMemberObj"])
	onDeleteSpaceMemberObj(id: String, spaceId: String, userId: String): SpaceMemberObj
		@aws_subscribe(mutations: ["deleteSpaceMemberObj"])
	onCreateGalleryMemberObj(id: String, galleryId: String, userId: String): GalleryMemberObj
		@aws_subscribe(mutations: ["createGalleryMemberObj"])
	onUpdateGalleryMemberObj(id: String, galleryId: String, userId: String): GalleryMemberObj
		@aws_subscribe(mutations: ["updateGalleryMemberObj"])
	onDeleteGalleryMemberObj(id: String, galleryId: String, userId: String): GalleryMemberObj
		@aws_subscribe(mutations: ["deleteGalleryMemberObj"])
	onCreateVerseMemberObj(id: String, verseId: String, userId: String): VerseMemberObj
		@aws_subscribe(mutations: ["createVerseMemberObj"])
	onUpdateVerseMemberObj(id: String, verseId: String, userId: String): VerseMemberObj
		@aws_subscribe(mutations: ["updateVerseMemberObj"])
	onDeleteVerseMemberObj(id: String, verseId: String, userId: String): VerseMemberObj
		@aws_subscribe(mutations: ["deleteVerseMemberObj"])
	onCreateRetroMemberObj(id: String, retroId: String, userId: String): RetroMemberObj
		@aws_subscribe(mutations: ["createRetroMemberObj"])
	onUpdateRetroMemberObj(id: String, retroId: String, userId: String): RetroMemberObj
		@aws_subscribe(mutations: ["updateRetroMemberObj"])
	onDeleteRetroMemberObj(id: String, retroId: String, userId: String): RetroMemberObj
		@aws_subscribe(mutations: ["deleteRetroMemberObj"])
}